addTaunt("20th Cent Fox Theme", {"taunts/thab1/props/20th_century_fox.mp3"}, "props", "both", {"talk"})
addTaunt("All Your Base", {"taunts/thab1/props/allyourbasearebelongtous.mp3"}, "props", "both", {"music"})
addTaunt("Most Annoying Sound", {"taunts/thab1/props/annoying_sound.mp3"}, "props", "both", {"talk"})
addTaunt("Another one bites the dust", {"taunts/thab1/props/another_one_bites_the_dust.mp3"}, "props", "both", {"talk"})
addTaunt("Atatatatatatata!", {"taunts/thab1/props/atatata.mp3"}, "props", "both", {"talk"})
addTaunt("A-Team", {"taunts/thab1/props/ateam.mp3"}, "props", "both", {"talk"})
addTaunt("Badgers", {"taunts/thab1/props/badger.mp3"}, "props", "both", {"talk"})
addTaunt("Balls of steel", {"taunts/thab1/props/balls_of_steel.mp3"}, "props", "both", {"talk"})
addTaunt("Banana Phone", {"taunts/thab1/props/banana_phone.mp3"}, "props", "both", {"music"})
addTaunt("Barbie Girl", {"taunts/thab1/props/barbiegirl.mp3"}, "props", "both", {"music"})
addTaunt("Do a barrel roll", {"taunts/thab1/props/barrelroll.mp3"}, "props", "both", {"talk"})
addTaunt("Benny Hill", {"taunts/thab1/props/bennyhill.mp3"}, "props", "both", {"music"})
addTaunt("Billy Mays", {"taunts/thab1/props/billymays1.mp3","taunts/thab1/props/billymays2.mp3","taunts/thab1/props/billymays3.mp3","taunts/thab1/props/billymays4.mp3","taunts/thab1/props/billymays5.mp3","taunts/thab1/props/billymays6.mp3","taunts/thab1/props/billymays7.mp3","taunts/thab1/props/billymays8.mp3","taunts/thab1/props/billymays9.mp3","taunts/thab1/props/billymays10.mp3"}, "props", "both", {"talk"})
addTaunt("Bird is the word", {"taunts/thab1/props/bird_word.mp3"}, "props", "both", {"music"})
addTaunt("Butters", {"taunts/thab1/props/butters.mp3"}, "props", "both", {"talk"})
addTaunt("Cable Guy", {"taunts/thab1/props/cableguy.mp3"}, "props", "both", {"talk"})
addTaunt("Call Me Maybe", {"taunts/thab1/props/call_me_maybe.mp3"}, "props", "both", {"music"})
addTaunt("Call On Me", {"taunts/thab1/props/callonme.mp3"}, "props", "both", {"music"})
addTaunt("Can't Touch This", {"taunts/thab1/props/cant_touch_this.mp3"}, "props", "both", {"music"})
addTaunt("Careless Whisper", {"taunts/thab1/props/carelesswhisper.mp3"}, "props", "both", {"music"})
addTaunt("Car Honk", {"taunts/thab1/props/carhonk.mp3"}, "props", "both", {"sound"})
addTaunt("Celebration", {"taunts/thab1/props/celebration.mp3"}, "props", "both", {"music"})
addTaunt("Chacarron", {"taunts/thab1/props/chacarron.mp3"}, "props", "both", {"music"})
addTaunt("Charge", {"taunts/thab1/props/charge.mp3"}, "props", "both", {"music"})
addTaunt("Club 1", {"taunts/thab1/props/club_music.mp3"}, "props", "both", {"music"})
addTaunt("Club 2", {"taunts/thab1/props/club_music2.mp3"}, "props", "both", {"music"})
addTaunt("Club 3", {"taunts/thab1/props/clubsound.mp3"}, "props", "both", {"music"})
addTaunt("Cod Dub", {"taunts/thab1/props/cod_dub.mp3"}, "props", "both", {"music"})
addTaunt("Cornholio", {"taunts/thab1/props/cornholio.mp3"}, "props", "both", {"talk"})
addTaunt("Crocodile", {"taunts/thab1/props/crocodile.mp3"}, "props", "both", {"music"})
addTaunt("Darude", {"taunts/thab1/props/darude.mp3"}, "props", "both", {"music"})
addTaunt("Daym", {"taunts/thab1/props/daym.mp3"}, "props", "both", {"music"})
addTaunt("Derpsong", {"taunts/thab1/props/derpsong.mp3"}, "props", "both", {"music"})
addTaunt("Destination", {"taunts/thab1/props/destination.mp3"}, "props", "both", {"music"})
addTaunt("Dodo", {"taunts/thab1/props/dodo.mp3"}, "props", "both", {"sound"})
addTaunt("Doh", {"taunts/thab1/props/doh.mp3"}, "props", "both", {"sound"})
addTaunt("Dr Evil", {"taunts/thab1/props/dr_evil.mp3"}, "props", "both", {"music"})
addTaunt("Drop it", {"taunts/thab1/props/drop_it.mp3"}, "props", "both", {"music"})
addTaunt("Duck Song", {"taunts/thab1/props/ducksong.mp3"}, "props", "both", {"music"})
addTaunt("Egeland", {"taunts/thab1/props/egeland.mp3"}, "props", "both", {"music"})
addTaunt("Epic Sax Guy", {"taunts/thab1/props/epicsaxguy.mp3"}, "props", "both", {"music"})
addTaunt("I'm So Excited", {"taunts/thab1/props/excited.mp3"}, "props", "both", {"music"})
addTaunt("The Final Countdown", {"taunts/thab1/props/finalcountdown.mp3"}, "props", "both", {"music"})
addTaunt("Gangnam Style", {"taunts/thab1/props/gangmanstyle.mp3"}, "props", "both", {"music"})
addTaunt("Gay Bar", {"taunts/thab1/props/gaybar.mp3"}, "props", "both", {"music"})
addTaunt("Get Hyper", {"taunts/thab1/props/get_hyper.mp3"}, "props", "both", {"music"})
addTaunt("Get To The Chopper", {"taunts/thab1/props/gettothechopper.mp3"}, "props", "both", {"talk"})
addTaunt("Ghostbusters", {"taunts/thab1/props/ghostbusters.mp3"}, "props", "both", {"music"})
addTaunt("Girls Cup", {"taunts/thab1/props/girlscup.mp3"}, "props", "both", {"music"})
addTaunt("MP - Go Away", {"taunts/thab1/props/go_away_or_i_shall.mp3"}, "props", "both", {"talk"})
addTaunt("Guiles Theme", {"taunts/thab1/props/guilestheme.mp3"}, "props", "both", {"music"})
addTaunt("Ha! Gaaay!", {"taunts/thab1/props/ha_gay.mp3"}, "props", "both", {"talk"})
addTaunt("Haddaway", {"taunts/thab1/props/haddaway.mp3"}, "props", "both", {"music"})
addTaunt("Hamster Dance", {"taunts/thab1/props/hamster_song.mp3"}, "props", "both", {"music"})
addTaunt("Weird He Man", {"taunts/thab1/props/he_man.mp3"}, "props", "both", {"music"})
addTaunt("Why you mad?", {"taunts/thab1/props/heff_to_be_mad.mp3"}, "props", "both", {"talk"})
addTaunt("I Will Survive", {"taunts/thab1/props/i_will_survive.mp3"}, "props", "both", {"music"})
addTaunt("I Like Turtles!", {"taunts/thab1/props/iliketurtles2.mp3"}, "props", "both", {"talk"})
addTaunt("I'm Blue", {"taunts/thab1/props/im_blue.mp3"}, "props", "both", {"music"})
addTaunt("Indiana Jones Theme", {"taunts/thab1/props/indiana_jones.mp3"}, "props", "both", {"music"})
addTaunt("It's a trap!", {"taunts/thab1/props/itsatrap.mp3"}, "props", "both", {"talk"})
addTaunt("Jackass Theme", {"taunts/thab1/props/jackass.mp3"}, "props", "both", {"music"})
addTaunt("Jeapardy Theme", {"taunts/thab1/props/jeopardy.mp3"}, "props", "both", {"music"})
addTaunt("Leeeeroy!", {"taunts/thab1/props/leeroy.mp3"}, "props", "both", {"talk"})
addTaunt("Let's Get It On", {"taunts/thab1/props/lets_get_it_on.mp3"}, "props", "both", {"music"})
addTaunt("Ready to Rumble", {"taunts/thab1/props/lets_get_ready_to.rumble.mp3"}, "props", "both", {"music"})
addTaunt("Excuse Me Princess", {"taunts/thab1/props/link_excuseme.mp3"}, "props", "both", {"talk"})
addTaunt("Livin' on a prayer", {"taunts/thab1/props/living_on_a_prayer.mp3"}, "props", "both", {"music"})
addTaunt("Mahnamahna", {"taunts/thab1/props/mahnamahna.mp3"}, "props", "both", {"music"})
addTaunt("Mario theme", {"taunts/thab1/props/mario.mp3"}, "props", "both", {"music"})
addTaunt("Miracle", {"taunts/thab1/props/miracle.mp3"}, "props", "both", {"music"})
addTaunt("MF - Creeping", {"taunts/thab1/props/morgan1.mp3"}, "props", "both", {"talk"})
addTaunt("My Milkshake", {"taunts/thab1/props/my_milkshake.mp3"}, "props", "both", {"music"})
addTaunt("Myrr Scream", {"taunts/thab1/props/myrr_scream.mp3"}, "props", "both", {"talk"})
addTaunt("Damn nature, you scary!", {"taunts/thab1/props/nature_scary.mp3"}, "props", "both", {"talk"})
addTaunt("Negative", {"taunts/thab1/props/negative.mp3"}, "props", "both", {"talk"})
addTaunt("Nomnom", {"taunts/thab1/props/nomnom.mp3"}, "props", "both", {"music"})
addTaunt("Not Unusual", {"taunts/thab1/props/not_unusual.mp3"}, "props", "both", {"music"})
addTaunt("Nyan cat", {"taunts/thab1/props/nyan_cat.mp3"}, "props", "both", {"music"})
addTaunt("He Will Pay", {"taunts/thab1/props/oh_yea_he_will_pay.mp3"}, "props", "both", {"talk"})
addTaunt("Do You Know the Muffin Man?", {"taunts/thab1/props/ok_i_will_tell_you.mp3"}, "props", "both", {"talk"})
addTaunt("Please Come Again", {"taunts/thab1/props/please_come_again.mp3"}, "props", "both", {"talk"})
addTaunt("Pokemon", {"taunts/thab1/props/pokemon.mp3"}, "props", "both", {"talk"})
addTaunt("Pokerface", {"taunts/thab1/props/pokerface.mp3"}, "props", "both", {"music"})
addTaunt("Portal Still Alive", {"taunts/thab1/props/portal_stillalive.mp3"}, "props", "both", {"music"})
addTaunt("Fresh Prince", {"taunts/thab1/props/prince_of_bel_air.mp3"}, "props", "both", {"music"})
addTaunt("Puddi", {"taunts/thab1/props/puddi.mp3"}, "props", "both", {"music"})
addTaunt("Rock you like a hurricane", {"taunts/thab1/props/rock_you_like_a_hurricane.mp3"}, "props", "both", {"music"})
addTaunt("Scatman", {"taunts/thab1/props/scatman.mp3"}, "props", "both", {"music"})
addTaunt("Seananners intro", {"taunts/thab1/props/seananners_intro.mp3"}, "props", "both", {"music"})
addTaunt("Sexy thang", {"taunts/thab1/props/sexy_thang.mp3"}, "props", "both", {"music"})
addTaunt("Shamwow!", {"taunts/thab1/props/shamwow.mp3"}, "props", "both", {"talk"})
addTaunt("Skrillex Goat", {"taunts/thab1/props/skrillex_goat.mp3"}, "props", "both", {"music"})
addTaunt("Snaaaaake", {"taunts/thab1/props/snaaake.mp3"}, "props", "both", {"talk"})
addTaunt("Snooping", {"taunts/thab1/props/snooping.mp3"}, "props", "both", {"talk"})
addTaunt("This Is Sparta!", {"taunts/thab1/props/sparta.mp3"}, "props", "both", {"talk"})
addTaunt("Spongebob Theme", {"taunts/thab1/props/spongebob.mp3"}, "props", "both", {"music"})
addTaunt("Spongebob Goofy Goober", {"taunts/thab1/props/spongebob2.mp3"}, "props", "both", {"music"})
addTaunt("Stamp on the ground", {"taunts/thab1/props/stamp_on_the_ground.mp3"}, "props", "both", {"music"})
addTaunt("Staying Alive", {"taunts/thab1/props/staying_alive.mp3"}, "props", "both", {"music"})
addTaunt("Suck my balls", {"taunts/thab1/props/suckballs.mp3"}, "props", "both", {"talk"})
addTaunt("Tard", {"taunts/thab1/props/tard.mp3"}, "props", "both", {"talk"})
addTaunt("The One And Only", {"taunts/thab1/props/theoneandonly.mp3"}, "props", "both", {"music"})
addTaunt("Too Sexy", {"taunts/thab1/props/too_sexy.mp3"}, "props", "both", {"music"})
addTaunt("Transformers", {"taunts/thab1/props/transformers.mp3"}, "props", "both", {"sound"})
addTaunt("Troll 1", {"taunts/thab1/props/troll1.mp3"}, "props", "both", {"music"})
addTaunt("Troll 2", {"taunts/thab1/props/troll2.mp3"}, "props", "both", {"music"})
addTaunt("Unicorns", {"taunts/thab1/props/unicorns.mp3"}, "props", "both", {"music"})
addTaunt("Universal Theme", {"taunts/thab1/props/universal.mp3"}, "props", "both", {"music"})
addTaunt("Walkin on Sunshine", {"taunts/thab1/props/walking_on_sunshine.mp3"}, "props", "both", {"music"})
addTaunt("Walla Bing Bang", {"taunts/thab1/props/walla_walla_bing_bang.mp3"}, "props", "both", {"music"})
addTaunt("I wanna rock!", {"taunts/thab1/props/wanna_rock.mp3"}, "props", "both", {"music"})
addTaunt("What does the fox say?", {"taunts/thab1/props/what_does_the_fox_say.mp3"}, "props", "both", {"music"})
addTaunt("What is wrong with you?!", {"taunts/thab1/props/what_is_wrong_with_you.mp3"}, "props", "both", {"talk"})
addTaunt("Wooooah!", {"taunts/thab1/props/woah.mp3"}, "props", "both", {"music"})
addTaunt("Wololo", {"taunts/thab1/props/wololo.mp3"}, "props", "both", {"talk"})
addTaunt("Homer Woohoo", {"taunts/thab1/props/woohoo.mp3"}, "props", "both", {"talk"})
addTaunt("Wub Wub", {"taunts/thab1/props/wubwub.mp3"}, "props", "both", {"music"})
addTaunt("Yo Adrianne!", {"taunts/thab1/props/yo_adrian.mp3"}, "props", "both", {"talk"})
addTaunt("Zoidberg", {"taunts/thab1/props/zoidberg.mp3"}, "props", "both", {"music"})
addTaunt("Banana Bus", {"taunts/thab1/props/banana-bus.mp3"}, "props", "both", {"music"})
addTaunt("Bananas Are Good", {"taunts/thab1/props/bananas-are-good.mp3"}, "props", "both", {"talk"})
addTaunt("Blablabla", {"taunts/thab1/props/blablabla.mp3"}, "props", "both", {"music"})
addTaunt("Bye Have a Great Time", {"taunts/thab1/props/bye_have_a_great_time.mp3"}, "props", "both", {"talk"})
addTaunt("Follow Silly Sound", {"taunts/thab1/props/claptrap-follow-the-silly-sound.mp3"}, "props", "both", {"Claptrap"})
addTaunt("I am Alive", {"taunts/thab1/props/claptrap-haha-im-alive.mp3"}, "props", "both", {"Claptrap"})
addTaunt("I'm Over Here", {"taunts/thab1/props/claptrap-im-over-here.mp3"}, "props", "both", {"Claptrap"})
addTaunt("Oh No Going to Die", {"taunts/thab1/props/claptrap-oh-no-going-to-die.mp3"}, "props", "both", {"Claptrap"})
addTaunt("Please Don't Shoot Me", {"taunts/thab1/props/claptrap-please-dont-shot-me.mp3"}, "props", "both", {"Claptrap"})
addTaunt("This way!", {"taunts/thab1/props/claptrap-this-way.mp3"}, "props", "both", {"Claptrap"})
addTaunt("Wait, is that...?", {"taunts/thab1/props/claptrap-wait-is-that.mp3"}, "props", "both", {"Claptrap"})
addTaunt("GladOS - Moron", {"taunts/thab1/props/designed_to_be_a_moron.mp3"}, "props", "both", {"talk"})
addTaunt("Dinkleberg", {"taunts/thab1/props/dinkleberg.mp3"}, "props", "both", {"talk"})
addTaunt("I'm the doctor!", {"taunts/thab1/props/doctor-01.mp3","taunts/thab1/props/doctor-02.mp3","taunts/thab1/props/doctor-03.mp3","taunts/thab1/props/doctor-04.mp3","taunts/thab1/props/doctor-05.mp3"}, "props", "both", {"talk"})
addTaunt("I'm a virgin!", {"taunts/thab1/props/eclipse.mp3"}, "props", "both", {"talk"})
addTaunt("Everything is awesome", {"taunts/thab1/props/everythingisawesome.mp3"}, "props", "both", {"music"})
addTaunt("Kermit - Corpse", {"taunts/thab1/props/kermit-corpse.mp3"}, "props", "both", {"music"})
addTaunt("Kermit - Screams", {"taunts/thab1/props/kermit-gonna-make.mp3"}, "props", "both", {"music"})
addTaunt("Kermit - Minorities", {"taunts/thab1/props/kermit-the-world.mp3"}, "props", "both", {"music"})
addTaunt("My Heart Will Go On", {"taunts/thab1/props/my-heart-will-go-on.mp3"}, "props", "both", {"music"})
addTaunt("Class, first lesson...", {"taunts/thab1/props/sark-01.mp3"}, "props", "both", {"talk"})
addTaunt("Trololololol", {"taunts/thab1/props/trololololol.mp3"}, "props", "both", {"music"})
addTaunt("Smoke Every Day", {"taunts/thab1/props/smoke-weed.mp3"}, "props", "both", {"music"})
addTaunt("Yodel", {"taunts/thab1/props/yodel-franz-lang.mp3"}, "props", "both", {"music"})
addTaunt("ACDC", {"taunts/thab1/props/1-1.mp3"}, "props", "both", {"music"})
addTaunt("Axel F", {"taunts/thab1/props/1-21.mp3"}, "props", "both", {"music"})
addTaunt("24", {"taunts/thab1/props/1-24.mp3"}, "props", "both", {"sound"})
addTaunt("Chaaaarlieeee", {"taunts/thab1/props/1-37.mp3"}, "props", "both", {"talk"})
addTaunt("Circus", {"taunts/thab1/props/1-38.mp3"}, "props", "both", {"music"})
addTaunt("Circus Afro", {"taunts/thab1/props/1-39.mp3"}, "props", "both", {"music"})
addTaunt("Crickets", {"taunts/thab1/props/1-40.mp3"}, "props", "both", {"sounds"})
addTaunt("Disney Theme", {"taunts/thab1/props/1-41.mp3"}, "props", "both", {"music"})
addTaunt("Dum dum dummmmm", {"taunts/thab1/props/1-43.mp3"}, "props", "both", {"music"})
addTaunt("Never gonna give you up", {"taunts/thab1/props/1-44.mp3"}, "props", "both", {"music"})
addTaunt("Eye of the Tiger", {"taunts/thab1/props/1-47.mp3"}, "props", "both", {"music"})
addTaunt("Tip Toes", {"taunts/thab1/props/1-51.mp3"}, "props", "both", {"sounds"})
addTaunt("Hakuna Matata", {"taunts/thab1/props/1-57.mp3"}, "props", "both", {"music"})
addTaunt("Hodor!", {"taunts/thab1/props/1-58.mp3"}, "props", "both", {"talk"})
addTaunt("Holy Shit!", {"taunts/thab1/props/1-59.mp3"}, "props", "both", {"talk"})
addTaunt("Inception Horn", {"taunts/thab1/props/1-62.mp3"}, "props", "both", {"sounds"})
addTaunt("Internet is for porn!", {"taunts/thab1/props/1-63.mp3"}, "props", "both", {"music"})
addTaunt("Pop goes the weasel", {"taunts/thab1/props/1-64.mp3"}, "props", "both", {"music"})
addTaunt("The Lion Sleeps Tonight", {"taunts/thab1/props/1-65.mp3"}, "props", "both", {"music"})
addTaunt("Keyboard Cat", {"taunts/thab1/props/1-66.mp3"}, "props", "both", {"music"})
addTaunt("Nokia Ringtone", {"taunts/thab1/props/1-68.mp3"}, "props", "both", {"music"})
addTaunt("Who scream", {"taunts/thab1/props/1-69.mp3"}, "props", "both", {"music"})
addTaunt("Pokemon Theme", {"taunts/thab1/props/1-72.mp3"}, "props", "both", {"music"})
addTaunt("Failure", {"taunts/thab1/props/1-73.mp3"}, "props", "both", {"sound"})

