addTaunt("Achievement Unlocked", { "taunts/thab2/props/achievementunlocked.mp3"}, "props", "both", {"sounds"})
addTaunt("Aint Nobdody Got Time", { "taunts/thab2/props/aintnobodygottimeforthat.mp3"}, "props", "both", {"talk"})
addTaunt("Air Raid Siren", { "taunts/thab2/props/airraidsiren.mp3"}, "props", "both", {"sounds"})
addTaunt("Alan!", { "taunts/thab2/props/alanalan.mp3"}, "props", "both", {"talk"})
addTaunt("All Aboard!", { "taunts/thab2/props/allaboard.mp3"}, "props", "both", {"music"})
addTaunt("All Your Base", { "taunts/thab2/props/allyourbase.mp3"}, "props", "both", {"talk"})
addTaunt("Andy Griffith Theme", { "taunts/thab2/props/andygriffithshowtheme.mp3"}, "props", "both", {"music"})
addTaunt("Angry Birds Theme", { "taunts/thab2/props/angrybirdstheme.mp3"}, "props", "both", {"music"})
addTaunt("Another Job Well Done", { "taunts/thab2/props/anotherjobwelldone.mp3"}, "props", "both", {"talk"})
addTaunt("Arrow In The Knee", { "taunts/thab2/props/arrowintheknee.mp3"}, "props", "both", {"talk"})
addTaunt("Arrow In The Knee short", { "taunts/thab2/props/arrowinthekneeshort.mp3"}, "props", "both", {"talk"})
addTaunt("Ass fuck!", { "taunts/thab2/props/assfuck.mp3"}, "props", "both", {"talk"})
addTaunt("Ay Caramba!", { "taunts/thab2/props/aycaramba.mp3"}, "props", "both", {"talk"})
addTaunt("Back In Time", { "taunts/thab2/props/backintime.mp3"}, "props", "both", {"music"})
addTaunt("Bad Feeling", { "taunts/thab2/props/badfeelings.mp3"}, "props", "both", {"talk"})
addTaunt("Badum tssss", { "taunts/thab2/props/badumtss.mp3"}, "props", "both", {"sounds"})
addTaunt("BatCat", { "taunts/thab2/props/batcat.mp3"}, "props", "both", {"music"})
addTaunt("Bazinga!", { "taunts/thab2/props/bazinga.mp3"}, "props", "both", {"talk"})
addTaunt("Bond", { "taunts/thab2/props/bond.mp3"}, "props", "both", {"talk"})
addTaunt("Boobies!", { "taunts/thab2/props/boobies.mp3"}, "props", "both", {"talk"})
addTaunt("Bowser Laugh 1", { "taunts/thab2/props/bowserlaugh1.mp3"}, "props", "both", {"sounds"})
addTaunt("Bowser Laugh 2", { "taunts/thab2/props/bowserlaugh2.mp3"}, "props", "both", {"sounds"})
addTaunt("Breaking Bad", { "taunts/thab2/props/breakingbad.mp3"}, "props", "both", {"music"})
addTaunt("Bring On The Trumpets!", { "taunts/thab2/props/bringonthetrumpets.mp3"}, "props", "both", {"talk"})
addTaunt("Bruh", { "taunts/thab2/props/bruh.mp3"}, "props", "both", {"talk"})
addTaunt("Burned", { "taunts/thab2/props/burned.mp3"}, "props", "both", {"talk"})
addTaunt("Cap One Goat", { "taunts/thab2/props/capitolonegoat.mp3"}, "props", "both", {"sounds"})
addTaunt("Cash Register", { "taunts/thab2/props/cashregister.mp3"}, "props", "both", {"sounds"})
addTaunt("Cavalry Charge", { "taunts/thab2/props/cavalrycharge.mp3"}, "hunters", "both", {"sounds"})
addTaunt("Cave Story", { "taunts/thab2/props/cavestory.mp3"}, "props", "both", {"sounds"})
addTaunt("Censor Beep", { "taunts/thab2/props/censoredbeep.mp3"}, "props", "both", {"sounds"})
addTaunt("Challenge Accepted", { "taunts/thab2/props/challengeaccepted.mp3"}, "props", "both", {"talk"})
addTaunt("Chan", { "taunts/thab2/props/chan.mp3"}, "props", "both", {"sounds"})
addTaunt("Chan Chan", { "taunts/thab2/props/chanchan.mp3"}, "props", "both", {"sounds"})
addTaunt("Chewbacca", { "taunts/thab2/props/chewbacca.mp3"}, "props", "both", {"sounds"})
addTaunt("Chicken Song", { "taunts/thab2/props/chickensong.mp3"}, "props", "both", {"music"})
addTaunt("Chocolate", { "taunts/thab2/props/chocolate.mp3"}, "props", "both", {"talk"})
addTaunt("Chuck Testa", { "taunts/thab2/props/chucktesta.mp3"}, "props", "both", {"talk"})
addTaunt("City Wok", { "taunts/thab2/props/citywokguy.mp3"}, "props", "both", {"talk"})
addTaunt("Clang lawandorder", { "taunts/thab2/props/clanglawandorder.mp3"}, "props", "both", {"sounds"})
addTaunt("Clock is ticking", { "taunts/thab2/props/clockisticking.mp3"}, "props", "both", {"talk"})
addTaunt("Colossus Yale", { "taunts/thab2/props/colossusyale.mp3"}, "props", "both", {"sounds"})
addTaunt("Consuelano", { "taunts/thab2/props/consuelano.mp3"}, "props", "both", {"talk"})
addTaunt("Cuek", { "taunts/thab2/props/cuek.mp3"}, "props", "both", {"sounds"})
addTaunt("damnitbonnieyouliedtome", { "taunts/thab2/props/damnitbonnieyouliedtome.mp3"}, "props", "both", {"talk"})
addTaunt("demomanisspy", { "taunts/thab2/props/demomanisspy.mp3"}, "props", "both", {"unfiled"})
addTaunt("diepotato", { "taunts/thab2/props/diepotato.mp3"}, "props", "both", {"unfiled"})
addTaunt("dirtybit", { "taunts/thab2/props/dirtybit.mp3"}, "props", "both", {"music"})
addTaunt("doeshelooklikeabitch", { "taunts/thab2/props/doeshelooklikeabitch.mp3"}, "props", "both", {"unfiled"})
addTaunt("donttasemebro", { "taunts/thab2/props/donttasemebro.mp3"}, "props", "both", {"unfiled"})
addTaunt("donttouchit", { "taunts/thab2/props/donttouchit.mp3"}, "props", "both", {"unfiled"})
addTaunt("dontyouwannalittletasteoftheglory", { "taunts/thab2/props/dontyouwannalittletasteoftheglory.mp3"}, "props", "both", {"unfiled"})
addTaunt("doublepoints", { "taunts/thab2/props/doublepoints.mp3"}, "props", "both", {"unfiled"})
addTaunt("doyoufeelluckypunk", { "taunts/thab2/props/doyoufeelluckypunk.mp3"}, "props", "both", {"unfiled"})
addTaunt("dramatic", { "taunts/thab2/props/dramatic.mp3"}, "props", "both", {"unfiled"})
addTaunt("droctagonapus", { "taunts/thab2/props/droctagonapus.mp3"}, "props", "both", {"unfiled"})
addTaunt("drogbaaa", { "taunts/thab2/props/drogbaaa.mp3"}, "props", "both", {"unfiled"})
addTaunt("drumroll", { "taunts/thab2/props/drumroll.mp3"}, "props", "both", {"unfiled"})
addTaunt("duckhuntdoglaugh", { "taunts/thab2/props/duckhuntdoglaugh.mp3"}, "props", "both", {"unfiled"})
addTaunt("dudecouldyoubemoregay", { "taunts/thab2/props/dudecouldyoubemoregay.mp3"}, "props", "both", {"unfiled"})
addTaunt("dumdumgumgum", { "taunts/thab2/props/dumdumgumgum.mp3"}, "props", "both", {"unfiled"})
addTaunt("eagle", { "taunts/thab2/props/eagle.mp3"}, "props", "both", {"unfiled"})
addTaunt("easypeasylemonsqueezy", { "taunts/thab2/props/easypeasylemonsqueezy.mp3"}, "props", "both", {"unfiled"})
addTaunt("einszweidreivier", { "taunts/thab2/props/einszweidreivier.mp3"}, "props", "both", {"unfiled"})
addTaunt("emergencyyodel", { "taunts/thab2/props/emergencyyodel.mp3"}, "props", "both", {"unfiled"})
addTaunt("epicmealtimecrow", { "taunts/thab2/props/epicmealtimecrow.mp3"}, "props", "both", {"unfiled"})
addTaunt("error", { "taunts/thab2/props/error.mp3"}, "props", "both", {"unfiled"})
addTaunt("everdancewiththedevil", { "taunts/thab2/props/everdancewiththedevil.mp3"}, "props", "both", {"unfiled"})
addTaunt("everyone", { "taunts/thab2/props/everyone.mp3"}, "props", "both", {"unfiled"})
addTaunt("evillaugh", { "taunts/thab2/props/evillaugh.mp3"}, "props", "both", {"unfiled"})
addTaunt("excellent", { "taunts/thab2/props/excellent.mp3"}, "props", "both", {"unfiled"})
addTaunt("falconpunch", { "taunts/thab2/props/falconpunch.mp3"}, "props", "both", {"unfiled"})
addTaunt("fascinating", { "taunts/thab2/props/fascinating.mp3"}, "props", "both", {"unfiled"})
addTaunt("fatality", { "taunts/thab2/props/fatality.mp3"}, "props", "both", {"unfiled"})
addTaunt("finalfantasyvictory", { "taunts/thab2/props/finalfantasyvictory.mp3"}, "props", "both", {"unfiled"})
addTaunt("finishhim", { "taunts/thab2/props/finishhim.mp3"}, "props", "both", {"unfiled"})
addTaunt("fivenightsatfreddysscream", { "taunts/thab2/props/fivenightsatfreddysscream.mp3"}, "props", "both", {"unfiled"})
addTaunt("flyingbird", { "taunts/thab2/props/flyingbird.mp3"}, "props", "both", {"unfiled"})
addTaunt("fuckoff", { "taunts/thab2/props/fuckoff.mp3"}, "props", "both", {"unfiled"})
addTaunt("fusrodah", { "taunts/thab2/props/fusrodah.mp3"}, "props", "both", {"unfiled"})
addTaunt("gameoverman", { "taunts/thab2/props/gameoverman.mp3"}, "props", "both", {"unfiled"})
addTaunt("gayfish", { "taunts/thab2/props/gayfish.mp3"}, "props", "both", {"unfiled"})
addTaunt("gayluigi", { "taunts/thab2/props/gayluigi.mp3"}, "props", "both", {"unfiled"})
addTaunt("gentlemen", { "taunts/thab2/props/gentlemen.mp3"}, "props", "both", {"unfiled"})
addTaunt("getoutofheredewey", { "taunts/thab2/props/getoutofheredewey.mp3"}, "props", "both", {"unfiled"})
addTaunt("getthatcornoutofmyface", { "taunts/thab2/props/getthatcornoutofmyface.mp3"}, "props", "both", {"unfiled"})
addTaunt("getthefuckoutmyfacewiththatshit", { "taunts/thab2/props/getthefuckoutmyfacewiththatshit.mp3"}, "props", "both", {"unfiled"})
addTaunt("gianthamsandwhich", { "taunts/thab2/props/gianthamsandwhich.mp3"}, "props", "both", {"unfiled"})
addTaunt("giggitygiggity", { "taunts/thab2/props/giggitygiggity.mp3"}, "props", "both", {"unfiled"})
addTaunt("gobbluthchickendance", { "taunts/thab2/props/gobbluthchickendance.mp3"}, "props", "both", {"unfiled"})
addTaunt("godzillaroar", { "taunts/thab2/props/godzillaroar.mp3"}, "props", "both", {"unfiled"})
addTaunt("gofuckyourself", { "taunts/thab2/props/gofuckyourself.mp3"}, "props", "both", {"unfiled"})
addTaunt("gong", { "taunts/thab2/props/gong.mp3"}, "props", "both", {"unfiled"})
addTaunt("goodnewseveryone", { "taunts/thab2/props/goodnewseveryone.mp3"}, "props", "both", {"unfiled"})
addTaunt("greatscott", { "taunts/thab2/props/greatscott.mp3"}, "props", "both", {"unfiled"})
addTaunt("greatsuccess", { "taunts/thab2/props/greatsuccess.mp3"}, "props", "both", {"unfiled"})
addTaunt("gunshots", { "taunts/thab2/props/gunshots.mp3"}, "props", "both", {"unfiled"})
addTaunt("haaaax", { "taunts/thab2/props/haaaax.mp3"}, "props", "both", {"unfiled"})
addTaunt("hadouken", { "taunts/thab2/props/hadouken.mp3"}, "props", "both", {"unfiled"})
addTaunt("haha", { "taunts/thab2/props/haha.mp3"}, "props", "both", {"unfiled"})
addTaunt("hallelujahlong", { "taunts/thab2/props/hallelujahlong.mp3"}, "props", "both", {"unfiled"})
addTaunt("hallelujahshort", { "taunts/thab2/props/hallelujahshort.mp3"}, "props", "both", {"unfiled"})
addTaunt("happycow", { "taunts/thab2/props/happycow.mp3"}, "props", "both", {"unfiled"})
addTaunt("happytreefriends", { "taunts/thab2/props/happytreefriends.mp3"}, "props", "both", {"unfiled"})
addTaunt("harlemshake", { "taunts/thab2/props/harlemshake.mp3"}, "props", "both", {"unfiled"})
addTaunt("hastalavistababy", { "taunts/thab2/props/hastalavistababy.mp3"}, "props", "both", {"unfiled"})
addTaunt("headshot", { "taunts/thab2/props/headshot.mp3"}, "props", "both", {"unfiled"})
addTaunt("hehhehalright", { "taunts/thab2/props/hehhehalright.mp3"}, "props", "both", {"unfiled"})
addTaunt("helloooo", { "taunts/thab2/props/helloooo.mp3"}, "props", "both", {"unfiled"})
addTaunt("heyapple", { "taunts/thab2/props/heyapple.mp3"}, "props", "both", {"unfiled"})
addTaunt("hideyokids", { "taunts/thab2/props/hideyokids.mp3"}, "props", "both", {"unfiled"})
addTaunt("highfive", { "taunts/thab2/props/highfive.mp3"}, "props", "both", {"unfiled"})
addTaunt("hodor", { "taunts/thab2/props/hodor.mp3"}, "props", "both", {"unfiled"})
addTaunt("hodorhodor", { "taunts/thab2/props/hodorhodor.mp3"}, "props", "both", {"unfiled"})
addTaunt("holdit", { "taunts/thab2/props/holdit.mp3"}, "props", "both", {"unfiled"})
addTaunt("hollowichigolaugh", { "taunts/thab2/props/hollowichigolaugh.mp3"}, "props", "both", {"unfiled"})
addTaunt("hotelmariono", { "taunts/thab2/props/hotelmariono.mp3"}, "props", "both", {"unfiled"})
addTaunt("howarddeansscream", { "taunts/thab2/props/howarddeansscream.mp3"}, "props", "both", {"unfiled"})
addTaunt("hulksmash", { "taunts/thab2/props/hulksmash.mp3"}, "props", "both", {"unfiled"})
addTaunt("iamthegreatcornholio", { "taunts/thab2/props/iamthegreatcornholio.mp3"}, "props", "both", {"unfiled"})
addTaunt("icanseethefuture", { "taunts/thab2/props/icanseethefuture.mp3"}, "props", "both", {"unfiled"})
addTaunt("icantbelivethathappend", { "taunts/thab2/props/icantbelivethathappend.mp3"}, "props", "both", {"unfiled"})
addTaunt("idontwanttoliveonthisplanetanymore", { "taunts/thab2/props/idontwanttoliveonthisplanetanymore.mp3"}, "props", "both", {"unfiled"})
addTaunt("idowhatiwant", { "taunts/thab2/props/idowhatiwant.mp3"}, "props", "both", {"unfiled"})
addTaunt("ihavenoidea", { "taunts/thab2/props/ihavenoidea.mp3"}, "props", "both", {"unfiled"})
addTaunt("ijustwantedtocuddle", { "taunts/thab2/props/ijustwantedtocuddle.mp3"}, "props", "both", {"unfiled"})
addTaunt("iliketrains", { "taunts/thab2/props/iliketrains.mp3"}, "props", "both", {"unfiled"})
addTaunt("illbeback", { "taunts/thab2/props/illbeback.mp3"}, "props", "both", {"unfiled"})
addTaunt("illmakehimanoffer", { "taunts/thab2/props/illmakehimanoffer.mp3"}, "props", "both", {"unfiled"})
addTaunt("ilovelamp", { "taunts/thab2/props/ilovelamp.mp3"}, "props", "both", {"unfiled"})
addTaunt("imbackbaby", { "taunts/thab2/props/imbackbaby.mp3"}, "props", "both", {"unfiled"})
addTaunt("imbadass", { "taunts/thab2/props/imbadass.mp3"}, "props", "both", {"unfiled"})
addTaunt("imoldgregg", { "taunts/thab2/props/imoldgregg.mp3"}, "props", "both", {"unfiled"})
addTaunt("imoldgregglong", { "taunts/thab2/props/imoldgregglong.mp3"}, "props", "both", {"unfiled"})
addTaunt("imrickjamesbitch", { "taunts/thab2/props/imrickjamesbitch.mp3"}, "props", "both", {"unfiled"})
addTaunt("imyourfather", { "taunts/thab2/props/imyourfather.mp3"}, "props", "both", {"unfiled"})
addTaunt("inamerica", { "taunts/thab2/props/inamerica.mp3"}, "props", "both", {"unfiled"})
addTaunt("iseeyou", { "taunts/thab2/props/iseeyou.mp3"}, "props", "both", {"unfiled"})
addTaunt("issuchathingevenpossible", { "taunts/thab2/props/issuchathingevenpossible.mp3"}, "props", "both", {"unfiled"})
addTaunt("itsadinosaur", { "taunts/thab2/props/itsadinosaur.mp3"}, "props", "both", {"unfiled"})
addTaunt("itsaverynice", { "taunts/thab2/props/itsaverynice.mp3"}, "props", "both", {"unfiled"})
addTaunt("itsclobberintime", { "taunts/thab2/props/itsclobberintime.mp3"}, "props", "both", {"unfiled"})
addTaunt("itsgone", { "taunts/thab2/props/itsgone.mp3"}, "props", "both", {"unfiled"})
addTaunt("itsmorphintime", { "taunts/thab2/props/itsmorphintime.mp3"}, "props", "both", {"unfiled"})
addTaunt("itspeanutbutterjellytime", { "taunts/thab2/props/itspeanutbutterjellytime.mp3"}, "props", "both", {"unfiled"})
addTaunt("itstimetoduel", { "taunts/thab2/props/itstimetoduel.mp3"}, "props", "both", {"unfiled"})
addTaunt("iwanttoplayagame", { "taunts/thab2/props/iwanttoplayagame.mp3"}, "props", "both", {"unfiled"})
addTaunt("iwasfrozentoday", { "taunts/thab2/props/iwasfrozentoday.mp3"}, "props", "both", {"unfiled"})
addTaunt("jeopardy", { "taunts/thab2/props/jeopardy.mp3"}, "props", "both", {"unfiled"})
addTaunt("justcantgetenough", { "taunts/thab2/props/justcantgetenough.mp3"}, "props", "both", {"unfiled"})
addTaunt("justdoit", { "taunts/thab2/props/justdoit.mp3"}, "props", "both", {"unfiled"})
addTaunt("kamehameha", { "taunts/thab2/props/kamehameha.mp3"}, "props", "both", {"unfiled"})
addTaunt("kelsoburn", { "taunts/thab2/props/kelsoburn.mp3"}, "props", "both", {"unfiled"})
addTaunt("khaaaaaan", { "taunts/thab2/props/khaaaaaan.mp3"}, "props", "both", {"unfiled"})
addTaunt("knife", { "taunts/thab2/props/knife.mp3"}, "props", "both", {"unfiled"})
addTaunt("kylesmomisabitch", { "taunts/thab2/props/kylesmomisabitch.mp3"}, "props", "both", {"unfiled"})
addTaunt("lalalalala", { "taunts/thab2/props/lalalalala.mp3"}, "props", "both", {"unfiled"})
addTaunt("lazor", { "taunts/thab2/props/lazor.mp3"}, "props", "both", {"unfiled"})
addTaunt("leavebritneyalone", { "taunts/thab2/props/leavebritneyalone.mp3"}, "props", "both", {"unfiled"})
addTaunt("legendary", { "taunts/thab2/props/legendary.mp3"}, "props", "both", {"unfiled"})
addTaunt("lexluthorwrong", { "taunts/thab2/props/lexluthorwrong.mp3"}, "props", "both", {"unfiled"})
addTaunt("lightsaberon", { "taunts/thab2/props/lightsaberon.mp3"}, "props", "both", {"unfiled"})
addTaunt("liveordie", { "taunts/thab2/props/liveordie.mp3"}, "props", "both", {"unfiled"})
addTaunt("looneytunes", { "taunts/thab2/props/looneytunes.mp3"}, "props", "both", {"unfiled"})
addTaunt("lotsaspaghetti", { "taunts/thab2/props/lotsaspaghetti.mp3"}, "props", "both", {"unfiled"})
addTaunt("mahboi", { "taunts/thab2/props/mahboi.mp3"}, "props", "both", {"unfiled"})
addTaunt("makinbaconpancakes", { "taunts/thab2/props/makinbaconpancakes.mp3"}, "props", "both", {"unfiled"})
addTaunt("mario", { "taunts/thab2/props/mario.mp3"}, "props", "both", {"unfiled"})
addTaunt("mariocoin", { "taunts/thab2/props/mariocoin.mp3"}, "props", "both", {"unfiled"})
addTaunt("mathematical", { "taunts/thab2/props/mathematical.mp3"}, "props", "both", {"unfiled"})
addTaunt("mbisonofcourse", { "taunts/thab2/props/mbisonofcourse.mp3"}, "props", "both", {"unfiled"})
addTaunt("mbisonyesyes", { "taunts/thab2/props/mbisonyesyes.mp3"}, "props", "both", {"unfiled"})
addTaunt("merrychristmasyoufilthyanimal", { "taunts/thab2/props/merrychristmasyoufilthyanimal.mp3"}, "props", "both", {"unfiled"})
addTaunt("mineturtlehello", { "taunts/thab2/props/mineturtlehello.mp3"}, "props", "both", {"unfiled"})
addTaunt("mmmwhatchasay", { "taunts/thab2/props/mmmwhatchasay.mp3"}, "props", "both", {"unfiled"})
addTaunt("monsieurhood", { "taunts/thab2/props/monsieurhood.mp3"}, "props", "both", {"unfiled"})
addTaunt("monsterkill", { "taunts/thab2/props/monsterkill.mp3"}, "props", "both", {"unfiled"})
addTaunt("mordorhorn", { "taunts/thab2/props/mordorhorn.mp3"}, "props", "both", {"unfiled"})
addTaunt("more", { "taunts/thab2/props/more.mp3"}, "props", "both", {"unfiled"})
addTaunt("moreinput", { "taunts/thab2/props/moreinput.mp3"}, "props", "both", {"unfiled"})
addTaunt("morphingtime", { "taunts/thab2/props/morphingtime.mp3"}, "props", "both", {"unfiled"})
addTaunt("moseisleycantina", { "taunts/thab2/props/moseisleycantina.mp3"}, "props", "both", {"unfiled"})
addTaunt("motherfuckingsnakes", { "taunts/thab2/props/motherfuckingsnakes.mp3"}, "props", "both", {"unfiled"})
addTaunt("mudkip", { "taunts/thab2/props/mudkip.mp3"}, "props", "both", {"unfiled"})
addTaunt("murloc", { "taunts/thab2/props/murloc.mp3"}, "props", "both", {"unfiled"})
addTaunt("musicaldoodle", { "taunts/thab2/props/musicaldoodle.mp3"}, "props", "both", {"unfiled"})
addTaunt("myleg", { "taunts/thab2/props/myleg.mp3"}, "props", "both", {"unfiled"})
addTaunt("mymom", { "taunts/thab2/props/mymom.mp3"}, "props", "both", {"unfiled"})
addTaunt("myprecious", { "taunts/thab2/props/myprecious.mp3"}, "props", "both", {"unfiled"})
addTaunt("narwhals", { "taunts/thab2/props/narwhals.mp3"}, "props", "both", {"unfiled"})
addTaunt("nazgulscream", { "taunts/thab2/props/nazgulscream.mp3"}, "props", "both", {"unfiled"})
addTaunt("nba", { "taunts/thab2/props/nba.mp3"}, "props", "both", {"unfiled"})
addTaunt("needadispenserhere", { "taunts/thab2/props/needadispenserhere.mp3"}, "props", "both", {"unfiled"})
addTaunt("nein", { "taunts/thab2/props/nein.mp3"}, "props", "both", {"unfiled"})
addTaunt("nemesisstars", { "taunts/thab2/props/nemesisstars.mp3"}, "props", "both", {"unfiled"})
addTaunt("nerdslaughing", { "taunts/thab2/props/nerdslaughing.mp3"}, "props", "both", {"unfiled"})
addTaunt("nighttimedaytime", { "taunts/thab2/props/nighttimedaytime.mp3"}, "props", "both", {"unfiled"})
addTaunt("nightvision", { "taunts/thab2/props/nightvision.mp3"}, "props", "both", {"unfiled"})
addTaunt("nobodyexpectsthespanishinquisitionlong", { "taunts/thab2/props/nobodyexpectsthespanishinquisitionlong.mp3"}, "props", "both", {"unfiled"})
addTaunt("nobodyexpectsthespanishinquisitionshort", { "taunts/thab2/props/nobodyexpectsthespanishinquisitionshort.mp3"}, "props", "both", {"unfiled"})
addTaunt("nodaddynooooo", { "taunts/thab2/props/nodaddynooooo.mp3"}, "props", "both", {"unfiled"})
addTaunt("nodisassemble", { "taunts/thab2/props/nodisassemble.mp3"}, "props", "both", {"unfiled"})
addTaunt("nofuckincookies", { "taunts/thab2/props/nofuckincookies.mp3"}, "props", "both", {"unfiled"})
addTaunt("nooo", { "taunts/thab2/props/nooo.mp3"}, "props", "both", {"unfiled"})
addTaunt("nope", { "taunts/thab2/props/nope.mp3"}, "props", "both", {"unfiled"})
addTaunt("norunningaroundthepool", { "taunts/thab2/props/norunningaroundthepool.mp3"}, "props", "both", {"unfiled"})
addTaunt("nostalgiacriticnerrrrrd", { "taunts/thab2/props/nostalgiacriticnerrrrrd.mp3"}, "props", "both", {"unfiled"})
addTaunt("nostalgiacriticthelaw", { "taunts/thab2/props/nostalgiacriticthelaw.mp3"}, "props", "both", {"unfiled"})
addTaunt("nothisispatrick", { "taunts/thab2/props/nothisispatrick.mp3"}, "props", "both", {"unfiled"})
addTaunt("noythatwouldbeyourmother", { "taunts/thab2/props/noythatwouldbeyourmother.mp3"}, "props", "both", {"unfiled"})
addTaunt("objection", { "taunts/thab2/props/objection.mp3"}, "props", "both", {"unfiled"})
addTaunt("ohlongjohnson", { "taunts/thab2/props/ohlongjohnson.mp3"}, "props", "both", {"unfiled"})
addTaunt("ohmy", { "taunts/thab2/props/ohmy.mp3"}, "props", "both", {"unfiled"})
addTaunt("ohmygod", { "taunts/thab2/props/ohmygod.mp3"}, "props", "both", {"unfiled"})
addTaunt("ohmygodidontcare", { "taunts/thab2/props/ohmygodidontcare.mp3"}, "props", "both", {"unfiled"})
addTaunt("ohmygodtheykilledkenny", { "taunts/thab2/props/ohmygodtheykilledkenny.mp3"}, "props", "both", {"unfiled"})
addTaunt("ohpieceofcandy", { "taunts/thab2/props/ohpieceofcandy.mp3"}, "props", "both", {"unfiled"})
addTaunt("ohthatsnasty", { "taunts/thab2/props/ohthatsnasty.mp3"}, "props", "both", {"unfiled"})
addTaunt("ohyeahwakeupyeah", { "taunts/thab2/props/ohyeahwakeupyeah.mp3"}, "props", "both", {"unfiled"})
addTaunt("omgtrampoline", { "taunts/thab2/props/omgtrampoline.mp3"}, "props", "both", {"unfiled"})
addTaunt("omgwhothehellcares", { "taunts/thab2/props/omgwhothehellcares.mp3"}, "props", "both", {"unfiled"})
addTaunt("ommmm", { "taunts/thab2/props/ommmm.mp3"}, "props", "both", {"unfiled"})
addTaunt("onedoesnotsimplywalkintomordor", { "taunts/thab2/props/onedoesnotsimplywalkintomordor.mp3"}, "props", "both", {"unfiled"})
addTaunt("onemilliondollars", { "taunts/thab2/props/onemilliondollars.mp3"}, "props", "both", {"unfiled"})
addTaunt("pacmantheme", { "taunts/thab2/props/pacmantheme.mp3"}, "props", "both", {"unfiled"})
addTaunt("pastaaa", { "taunts/thab2/props/pastaaa.mp3"}, "props", "both", {"unfiled"})
addTaunt("patricstarlelelele", { "taunts/thab2/props/patricstarlelelele.mp3"}, "props", "both", {"unfiled"})
addTaunt("paythatmanhismoney", { "taunts/thab2/props/paythatmanhismoney.mp3"}, "props", "both", {"unfiled"})
addTaunt("pedobearsong", { "taunts/thab2/props/pedobearsong.mp3"}, "props", "both", {"unfiled"})
addTaunt("penny", { "taunts/thab2/props/penny.mp3"}, "props", "both", {"unfiled"})
addTaunt("petergriffin", { "taunts/thab2/props/petergriffin.mp3"}, "props", "both", {"unfiled"})
addTaunt("pikachu", { "taunts/thab2/props/pikachu.mp3"}, "props", "both", {"unfiled"})
addTaunt("pingas", { "taunts/thab2/props/pingas.mp3"}, "props", "both", {"unfiled"})
addTaunt("pirate", { "taunts/thab2/props/pirate.mp3"}, "props", "both", {"unfiled"})
addTaunt("pokeballsound", { "taunts/thab2/props/pokeballsound.mp3"}, "props", "both", {"unfiled"})
addTaunt("pootis", { "taunts/thab2/props/pootis.mp3"}, "props", "both", {"unfiled"})
addTaunt("popeye", { "taunts/thab2/props/popeye.mp3"}, "props", "both", {"unfiled"})
addTaunt("powhaha", { "taunts/thab2/props/powhaha.mp3"}, "props", "both", {"unfiled"})
addTaunt("protectthedarkness", { "taunts/thab2/props/protectthedarkness.mp3"}, "props", "both", {"unfiled"})
addTaunt("punishhim", { "taunts/thab2/props/punishhim.mp3"}, "props", "both", {"unfiled"})
addTaunt("putthatcookiedown", { "taunts/thab2/props/putthatcookiedown.mp3"}, "props", "both", {"unfiled"})
addTaunt("r2d2", { "taunts/thab2/props/r2d2.mp3"}, "props", "both", {"unfiled"})
addTaunt("rabbids", { "taunts/thab2/props/rabbids.mp3"}, "props", "both", {"unfiled"})
addTaunt("rainbowsmakemecry", { "taunts/thab2/props/rainbowsmakemecry.mp3"}, "props", "both", {"unfiled"})
addTaunt("rayliottalaughing", { "taunts/thab2/props/rayliottalaughing.mp3"}, "props", "both", {"unfiled"})
addTaunt("residentevil", { "taunts/thab2/props/residentevil.mp3"}, "props", "both", {"unfiled"})
addTaunt("respectmyauthoritah", { "taunts/thab2/props/respectmyauthoritah.mp3"}, "props", "both", {"unfiled"})
addTaunt("retardalert", { "taunts/thab2/props/retardalert.mp3"}, "props", "both", {"unfiled"})
addTaunt("riiight", { "taunts/thab2/props/riiight.mp3"}, "props", "both", {"unfiled"})
addTaunt("ringringring", { "taunts/thab2/props/ringringring.mp3"}, "props", "both", {"unfiled"})
addTaunt("sadtrombone", { "taunts/thab2/props/sadtrombone.mp3"}, "props", "both", {"unfiled"})
addTaunt("sadtuba", { "taunts/thab2/props/sadtuba.mp3"}, "props", "both", {"unfiled"})
addTaunt("safetytorch", { "taunts/thab2/props/safetytorch.mp3"}, "props", "both", {"unfiled"})
addTaunt("sandwichmakemestrong", { "taunts/thab2/props/sandwichmakemestrong.mp3"}, "props", "both", {"unfiled"})
addTaunt("satellitephone", { "taunts/thab2/props/satellitephone.mp3"}, "props", "both", {"unfiled"})
addTaunt("sayhellotomylittlefriend", { "taunts/thab2/props/sayhellotomylittlefriend.mp3"}, "props", "both", {"unfiled"})
addTaunt("saymyname", { "taunts/thab2/props/saymyname.mp3"}, "props", "both", {"unfiled"})
addTaunt("screwyouguysimgoinghome", { "taunts/thab2/props/screwyouguysimgoinghome.mp3"}, "props", "both", {"unfiled"})
addTaunt("scusemewhileiwhipthisout", { "taunts/thab2/props/scusemewhileiwhipthisout.mp3"}, "props", "both", {"unfiled"})
addTaunt("sheriffcalliesyeehaw", { "taunts/thab2/props/sheriffcalliesyeehaw.mp3"}, "props", "both", {"unfiled"})
addTaunt("shoother", { "taunts/thab2/props/shoother.mp3"}, "props", "both", {"unfiled"})
addTaunt("shutthefuckup", { "taunts/thab2/props/shutthefuckup.mp3"}, "props", "both", {"unfiled"})
addTaunt("shutup", { "taunts/thab2/props/shutup.mp3"}, "props", "both", {"unfiled"})
addTaunt("shutupandtakemymoney", { "taunts/thab2/props/shutupandtakemymoney.mp3"}, "props", "both", {"unfiled"})
addTaunt("shutupmeg", { "taunts/thab2/props/shutupmeg.mp3"}, "props", "both", {"unfiled"})
addTaunt("silenceikillyou", { "taunts/thab2/props/silenceikillyou.mp3"}, "props", "both", {"unfiled"})
addTaunt("slowclap", { "taunts/thab2/props/slowclap.mp3"}, "props", "both", {"unfiled"})
addTaunt("solonggayboys", { "taunts/thab2/props/solonggayboys.mp3"}, "props", "both", {"unfiled"})
addTaunt("sonicrings", { "taunts/thab2/props/sonicrings.mp3"}, "props", "both", {"unfiled"})
addTaunt("spanishflea", { "taunts/thab2/props/spanishflea.mp3"}, "props", "both", {"unfiled"})
addTaunt("sparesomechange", { "taunts/thab2/props/sparesomechange.mp3"}, "props", "both", {"unfiled"})
addTaunt("spiderpig", { "taunts/thab2/props/spiderpig.mp3"}, "props", "both", {"unfiled"})
addTaunt("spinwithmechris", { "taunts/thab2/props/spinwithmechris.mp3"}, "props", "both", {"unfiled"})
addTaunt("stophammertime", { "taunts/thab2/props/stophammertime.mp3"}, "props", "both", {"unfiled"})
addTaunt("surprisemotherfucker", { "taunts/thab2/props/surprisemotherfucker.mp3"}, "props", "both", {"unfiled"})
addTaunt("swanee", { "taunts/thab2/props/swanee.mp3"}, "props", "both", {"unfiled"})
addTaunt("tada", { "taunts/thab2/props/tada.mp3"}, "props", "both", {"unfiled"})
addTaunt("tardis", { "taunts/thab2/props/tardis.mp3"}, "props", "both", {"unfiled"})
addTaunt("tedwilliamsvoice", { "taunts/thab2/props/tedwilliamsvoice.mp3"}, "props", "both", {"unfiled"})
addTaunt("thatsahugebitch", { "taunts/thab2/props/thatsahugebitch.mp3"}, "props", "both", {"unfiled"})
addTaunt("thatswhatshesaid", { "taunts/thab2/props/thatswhatshesaid.mp3"}, "props", "both", {"unfiled"})
addTaunt("theballsareinert", { "taunts/thab2/props/theballsareinert.mp3"}, "props", "both", {"unfiled"})
addTaunt("thegreatmightypoo", { "taunts/thab2/props/thegreatmightypoo.mp3"}, "props", "both", {"unfiled"})
addTaunt("theresabearinmyoatmeal", { "taunts/thab2/props/theresabearinmyoatmeal.mp3"}, "props", "both", {"unfiled"})
addTaunt("thetwilightzone", { "taunts/thab2/props/thetwilightzone.mp3"}, "props", "both", {"unfiled"})
addTaunt("theydrewfirstbloodnotme", { "taunts/thab2/props/theydrewfirstbloodnotme.mp3"}, "props", "both", {"unfiled"})
addTaunt("theythinkidontknowaboutthegospel", { "taunts/thab2/props/theythinkidontknowaboutthegospel.mp3"}, "props", "both", {"unfiled"})
addTaunt("thisismyboomstick", { "taunts/thab2/props/thisismyboomstick.mp3"}, "props", "both", {"unfiled"})
addTaunt("thisismydesign", { "taunts/thab2/props/thisismydesign.mp3"}, "props", "both", {"unfiled"})
addTaunt("thuglife", { "taunts/thab2/props/thuglife.mp3"}, "props", "both", {"unfiled"})
addTaunt("timmy", { "taunts/thab2/props/timmy.mp3"}, "props", "both", {"unfiled"})
addTaunt("tombriderangelofdarkness", { "taunts/thab2/props/tombriderangelofdarkness.mp3"}, "props", "both", {"unfiled"})
addTaunt("trexroar", { "taunts/thab2/props/trexroar.mp3"}, "props", "both", {"sounds"})
addTaunt("trunksgoesinsane", { "taunts/thab2/props/trunksgoesinsane.mp3"}, "props", "both", {"unfiled"})
addTaunt("tshirttime", { "taunts/thab2/props/tshirttime.mp3"}, "props", "both", {"unfiled"})
addTaunt("tumbleweed", { "taunts/thab2/props/tumbleweed.mp3"}, "props", "both", {"unfiled"})
addTaunt("unclefucker", { "taunts/thab2/props/unclefucker.mp3"}, "props", "both", {"unfiled"})
addTaunt("victoryff", { "taunts/thab2/props/victoryff.mp3"}, "props", "both", {"unfiled"})
addTaunt("victoryismine", { "taunts/thab2/props/victoryismine.mp3"}, "props", "both", {"unfiled"})
addTaunt("vindieselsaysfuck", { "taunts/thab2/props/vindieselsaysfuck.mp3"}, "props", "both", {"unfiled"})
addTaunt("voldemortslaugh", { "taunts/thab2/props/voldemortslaugh.mp3"}, "props", "both", {"unfiled"})
addTaunt("vuvuzela", { "taunts/thab2/props/vuvuzela.mp3"}, "props", "both", {"sounds"})
addTaunt("wakawaka", { "taunts/thab2/props/wakawaka.mp3"}, "props", "both", {"unfiled"})
addTaunt("wassup", { "taunts/thab2/props/wassup.mp3"}, "props", "both", {"unfiled"})
addTaunt("weareanonymous", { "taunts/thab2/props/weareanonymous.mp3"}, "props", "both", {"unfiled"})
addTaunt("wellywellywell", { "taunts/thab2/props/wellywellywell.mp3"}, "props", "both", {"unfiled"})
addTaunt("weshouldtakebikinibottom", { "taunts/thab2/props/weshouldtakebikinibottom.mp3"}, "props", "both", {"unfiled"})
addTaunt("whatsyourfavoritescarymovie", { "taunts/thab2/props/whatsyourfavoritescarymovie.mp3"}, "props", "both", {"unfiled"})
addTaunt("whatthedeuce", { "taunts/thab2/props/whatthedeuce.mp3"}, "props", "both", {"unfiled"})
addTaunt("whatthefuck", { "taunts/thab2/props/whatthefuck.mp3"}, "props", "both", {"unfiled"})
addTaunt("whereismymoneybitch", { "taunts/thab2/props/whereismymoneybitch.mp3"}, "props", "both", {"unfiled"})
addTaunt("wheresthatfourthchaosemerald", { "taunts/thab2/props/wheresthatfourthchaosemerald.mp3"}, "props", "both", {"unfiled"})
addTaunt("whip", { "taunts/thab2/props/whip.mp3"}, "props", "both", {"sounds"})
addTaunt("whoisyourdaddyandwhatishedo", { "taunts/thab2/props/whoisyourdaddyandwhatishedo.mp3"}, "props", "both", {"unfiled"})
addTaunt("whoopwhoopwhoop", { "taunts/thab2/props/whoopwhoopwhoop.mp3"}, "props", "both", {"unfiled"})
addTaunt("whowantstohearafunnyassjoke", { "taunts/thab2/props/whowantstohearafunnyassjoke.mp3"}, "props", "both", {"unfiled"})
addTaunt("whowantstoplayvideogames", { "taunts/thab2/props/whowantstoplayvideogames.mp3"}, "props", "both", {"unfiled"})
addTaunt("whysoserious", { "taunts/thab2/props/whysoserious.mp3"}, "props", "both", {"unfiled"})
addTaunt("wilhelmscream", { "taunts/thab2/props/wilhelmscream.mp3"}, "props", "both", {"unfiled"})
addTaunt("winteriscoming", { "taunts/thab2/props/winteriscoming.mp3"}, "props", "both", {"unfiled"})
addTaunt("wololo", { "taunts/thab2/props/wololo.mp3"}, "props", "both", {"unfiled"})
addTaunt("wrong", { "taunts/thab2/props/wrong.mp3"}, "props", "both", {"unfiled"})
addTaunt("wrongwrongwrongwrong", { "taunts/thab2/props/wrongwrongwrongwrong.mp3"}, "props", "both", {"unfiled"})
addTaunt("yay", { "taunts/thab2/props/yay.mp3"}, "props", "both", {"unfiled"})
addTaunt("yeahbuddy", { "taunts/thab2/props/yeahbuddy.mp3"}, "props", "both", {"unfiled"})
addTaunt("yippeekiyaymotherfucker", { "taunts/thab2/props/yippeekiyaymotherfucker.mp3"}, "props", "both", {"unfiled"})
addTaunt("youaresodumb", { "taunts/thab2/props/youaresodumb.mp3"}, "props", "both", {"unfiled"})
addTaunt("youatethispie", { "taunts/thab2/props/youatethispie.mp3"}, "props", "both", {"unfiled"})
addTaunt("yougoodylittletwoshoes", { "taunts/thab2/props/yougoodylittletwoshoes.mp3"}, "props", "both", {"unfiled"})
addTaunt("youhavefailthiscity", { "taunts/thab2/props/youhavefailthiscity.mp3"}, "props", "both", {"unfiled"})
addTaunt("youmustdie", { "taunts/thab2/props/youmustdie.mp3"}, "props", "both", {"unfiled"})
addTaunt("youpissedmeoff", { "taunts/thab2/props/youpissedmeoff.mp3"}, "props", "both", {"unfiled"})
addTaunt("yourmother", { "taunts/thab2/props/yourmother.mp3"}, "props", "both", {"unfiled"})
addTaunt("yourmusicisbad", { "taunts/thab2/props/yourmusicisbad.mp3"}, "props", "both", {"unfiled"})
addTaunt("zeldaitem", { "taunts/thab2/props/zeldaitem.mp3"}, "props", "both", {"sound"})
addTaunt("zeldasecret", { "taunts/thab2/props/zeldasecret.mp3"}, "props", "both", {"sound"})

