addTaunt("Bane - Permission to die", {"taunts/thab1/hunters/bane_permission.mp3"}, "hunters", "both", {"talk"})
addTaunt("Batman - I'm Batman", {"taunts/thab1/hunters/batman.mp3"}, "hunters", "both", {"talk"})
addTaunt("Duke - Out your ass", {"taunts/thab1/hunters/blow_it.mp3"}, "hunters", "both", {"DukeNukem"})
addTaunt("Headshot", {"taunts/thab1/hunters/boom_headshot.mp3"}, "hunters", "both", {"talk"})
addTaunt("Combobreaker!", {"taunts/thab1/hunters/combo_breaker.mp3"}, "hunters", "both", {"sound"})
addTaunt("Come at me", {"taunts/thab1/hunters/come_at_me.mp3"}, "hunters", "both", {"talk"})
addTaunt("Duke - Get some", {"taunts/thab1/hunters/come_get_some.mp3"}, "hunters", "both", {"DukeNukem"})
addTaunt("Taken - Find you", {"taunts/thab1/hunters/find_you.mp3"}, "hunters", "both", {"talk"})
addTaunt("Mighty scared", {"taunts/thab1/hunters/gassy_mexican.mp3"}, "hunters", "both", {"talk"})
addTaunt("Get over here!", {"taunts/thab1/hunters/getoverhere.mp3"}, "hunters", "both", {"talk"})
addTaunt("Duke - Bigger gun", {"taunts/thab1/hunters/gun_bigger.mp3"}, "hunters", "both", {"DukeNukem"})
addTaunt("Guttin you, boy", {"taunts/thab1/hunters/guttinyouboy.mp3"}, "hunters", "both", {"talk"})
addTaunt("Duke - Hail to the king", {"taunts/thab1/hunters/hail.mp3"}, "hunters", "both", {"DukeNukem"})
addTaunt("He-Man", {"taunts/thab1/hunters/he_man2.mp3"}, "hunters", "both", {"music"})
addTaunt("Guns don't kill people", {"taunts/thab1/hunters/i_kill_people.mp3"}, "hunters", "both", {"music"})
addTaunt("Jaws Theme", {"taunts/thab1/hunters/jaws.mp3"}, "hunters", "both", {"music"})
addTaunt("Forces eliminated", {"taunts/thab1/hunters/military.mp3"}, "hunters", "both", {"talk"})
addTaunt("MF - I can smell you", {"taunts/thab1/hunters/morgan2.mp3"}, "hunters", "both", {"talk"})
addTaunt("Duke - Out of gum", {"taunts/thab1/hunters/out_of_gum.mp3"}, "hunters", "both", {"DukeNukem"})
addTaunt("Overture", {"taunts/thab1/hunters/overture.mp3"}, "hunters", "both", {"music"})
addTaunt("Pacino", {"taunts/thab1/hunters/pacino.mp3"}, "hunters", "both", {"talk"})
addTaunt("Predator", {"taunts/thab1/hunters/predator.mp3"}, "hunters", "both", {"sound"})
addTaunt("Pulp Fiction - English!", {"taunts/thab1/hunters/pulp_fiction.mp3"}, "hunters", "both", {"talk"})
addTaunt("Full Retard", {"taunts/thab1/hunters/retard.mp3"}, "hunters", "both", {"talk"})
addTaunt("Run, Bitch", {"taunts/thab1/hunters/run_bitch_run.mp3"}, "hunters", "both", {"talk"})
addTaunt("Here's Johnny", {"taunts/thab1/hunters/the_shining.mp3"}, "hunters", "both", {"talk"})
addTaunt("Threat Neutralized", {"taunts/thab1/hunters/threat_neutralized.mp3"}, "hunters", "both", {"talk"})
addTaunt("THX Intro", {"taunts/thab1/hunters/thx_intro.mp3"}, "hunters", "both", {"sound"})
addTaunt("Vader - Don't know the power", {"taunts/thab1/hunters/you_dont_know_the_power.mp3"}, "hunters", "both", {"talk"})
addTaunt("Shall not pass!", {"taunts/thab1/hunters/you_shall_not_pass.mp3"}, "hunters", "both", {"talk"})
addTaunt("Vader - You underestimate", {"taunts/thab1/hunters/you_underestimate_the_power.mp3"}, "hunters", "both", {"talk"})
addTaunt("GladOs - Ex President", {"taunts/thab1/hunters/glados-president.mp3"}, "hunters", "both", {"talk"})
addTaunt("Dr Who - Exterminate", {"taunts/thab1/hunters/exterminate.mp3"}, "hunters", "both", {"talk"})
addTaunt("I'm watching you!", {"taunts/thab1/hunters/h1-2.mp3"}, "hunters", "both", {"talk"})
addTaunt("I'll cut your heart out with a spoon", {"taunts/thab1/hunters/h1-3.mp3"}, "hunters", "both", {"talk"})
addTaunt("Come quietly or trouble", {"taunts/thab1/hunters/h1-4.mp3"}, "hunters", "both", {"talk"})
addTaunt("I'll smash..", {"taunts/thab1/hunters/h1-5.mp3"}, "hunters", "both", {"talk"})
addTaunt("You move...", {"taunts/thab1/hunters/h1-6.mp3"}, "hunters", "both", {"talk"})
addTaunt("My domain!", {"taunts/thab1/hunters/h1-7.mp3"}, "hunters", "both", {"talk"})
addTaunt("Noticed", {"taunts/thab1/hunters/h1-8.mp3"}, "hunters", "both", {"sound"})
addTaunt("AOT Theme", {"taunts/thab1/hunters/h1-9.mp3"}, "hunters", "both", {"music"})
addTaunt("I really need a new gun!", {"taunts/thab1/hunters/h1-10.mp3"}, "hunters", "both", {"talk"})
addTaunt("I forgot to shoot something", {"taunts/thab1/hunters/h1-12.mp3"}, "hunters", "both", {"talk"})
addTaunt("Fav waste of bullets", {"taunts/thab1/hunters/h1-13.mp3"}, "hunters", "both", {"talk"})
addTaunt("Bond - Expect you to die", {"taunts/thab1/hunters/h1-15.mp3"}, "hunters", "both", {"talk"})
addTaunt("I see dead people", {"taunts/thab1/hunters/h1-16.mp3"}, "hunters", "both", {"talk"})
addTaunt("Ready Or Not", {"taunts/thab1/hunters/h1-18.mp3"}, "hunters", "both", {"music"})
addTaunt("MP - I command you", {"taunts/thab1/hunters/h1-19.mp3"}, "hunters", "both", {"talk"})
addTaunt("You get nothing!", {"taunts/thab1/hunters/h1-20.mp3"}, "hunters", "both", {"talk"})
addTaunt("Cops Theme", {"taunts/thab1/hunters/badboys.mp3"}, "hunters", "both", {"music"})
addTaunt("I'll be back", {"taunts/thab1/hunters/ill_be_back.mp3"}, "hunters", "both", {"talk"})
addTaunt("He will pay", {"taunts/thab1/hunters/oh_yea_he_will_pay.mp3"}, "hunters", "both", {"talk"})

